version: '3.8'
services:
  api:
    build: ./path/to/webapi
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
  web:
    build: ./path/to/angular
    ports:
      - "80:80"
