name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.11
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push .NET 8 Web API
        uses: docker/build-push-action@v2
        with:
          context: ./NpvCalculator.Api # Ensure this is the correct path
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/npv-calculator-api:latest

